# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11.0.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      PROFILE: format
      TEST_REPORTS: /tmp/test-reports
      
    steps:
      - checkout
        
      # run tests!
      - run: mvn test -Dtec.units.tck.profile=$PROFILE
      
      # copy TXT result to HTML report folder
      - run:
         cp ~/repo/./target/*.txt ~/repo/./target/tck-output

      # store test report folder as artifact
      - store_artifacts:
         path: ~/repo/./target/tck-output
  deployment:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11.0.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
        
      # run deployment!
      - run: mvn --batch-mode deploy -Dmaven.test.skip -DcreateDocs=true -s settings.xml
workflows:
  version: 2
  build_only:
    jobs:
      - build